[package]
name = "quinn_interop"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
bytes = "1.3"
futures = "0.3"
pin-utils = "0.1"
quinn = "0.9"
rcgen = "0.10"
rustls = {version = "0.20", features = ["dangerous_configuration", "quic"]}
tokio = {version ="1.23", features = ["full"]}